import { prisma } from '../../database';
import { NotFoundError } from '../../common/errors';
import { PaginatedResponse, PaginationQuery } from '../../common/schemas';
import { CreatePatientInput, UpdatePatientInput } from './patient.schema';

// Type is generated by Prisma after running `prisma generate`
// Using Prisma's inferred types from the client
type Patient = Awaited<ReturnType<typeof prisma.patient.findFirstOrThrow>>;

export class PatientService {
  async findAll(query: PaginationQuery): Promise<PaginatedResponse<Patient>> {
    const { page, limit } = query;
    const skip = (page - 1) * limit;

    const [data, total] = await Promise.all([
      prisma.patient.findMany({
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
      }),
      prisma.patient.count(),
    ]);

    return {
      data,
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit),
      },
    };
  }

  async findById(id: number): Promise<Patient> {
    const patient = await prisma.patient.findUnique({ where: { id } });
    if (!patient) {
      throw new NotFoundError('Patient');
    }
    return patient;
  }

  async create(input: CreatePatientInput): Promise<Patient> {
    return prisma.patient.create({ data: input });
  }

  async update(id: number, input: UpdatePatientInput): Promise<Patient> {
    await this.findById(id); // Ensure exists
    return prisma.patient.update({
      where: { id },
      data: input,
    });
  }

  async delete(id: number): Promise<void> {
    await this.findById(id); // Ensure exists
    await prisma.patient.delete({ where: { id } });
  }
}

export const patientService = new PatientService();
